// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mercury.proto

/*
Package mercury is a generated protocol buffer package.

It is generated from these files:
	mercury.proto

It has these top-level messages:
	MercuryMultiGetRequest
	MercuryMultiGetReply
	MercuryRequest
	MercuryReply
	Header
	UserField
*/
package mercury

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MercuryReply_CachePolicy int32

const (
	MercuryReply_CACHE_NO      MercuryReply_CachePolicy = 1
	MercuryReply_CACHE_PRIVATE MercuryReply_CachePolicy = 2
	MercuryReply_CACHE_PUBLIC  MercuryReply_CachePolicy = 3
)

var MercuryReply_CachePolicy_name = map[int32]string{
	1: "CACHE_NO",
	2: "CACHE_PRIVATE",
	3: "CACHE_PUBLIC",
}
var MercuryReply_CachePolicy_value = map[string]int32{
	"CACHE_NO":      1,
	"CACHE_PRIVATE": 2,
	"CACHE_PUBLIC":  3,
}

func (x MercuryReply_CachePolicy) Enum() *MercuryReply_CachePolicy {
	p := new(MercuryReply_CachePolicy)
	*p = x
	return p
}
func (x MercuryReply_CachePolicy) String() string {
	return proto.EnumName(MercuryReply_CachePolicy_name, int32(x))
}
func (x *MercuryReply_CachePolicy) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MercuryReply_CachePolicy_value, data, "MercuryReply_CachePolicy")
	if err != nil {
		return err
	}
	*x = MercuryReply_CachePolicy(value)
	return nil
}
func (MercuryReply_CachePolicy) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type MercuryMultiGetRequest struct {
	Request          []*MercuryRequest `protobuf:"bytes,1,rep,name=request" json:"request,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *MercuryMultiGetRequest) Reset()                    { *m = MercuryMultiGetRequest{} }
func (m *MercuryMultiGetRequest) String() string            { return proto.CompactTextString(m) }
func (*MercuryMultiGetRequest) ProtoMessage()               {}
func (*MercuryMultiGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MercuryMultiGetRequest) GetRequest() []*MercuryRequest {
	if m != nil {
		return m.Request
	}
	return nil
}

type MercuryMultiGetReply struct {
	Reply            []*MercuryReply `protobuf:"bytes,1,rep,name=reply" json:"reply,omitempty"`
	XXX_unrecognized []byte          `json:"-"`
}

func (m *MercuryMultiGetReply) Reset()                    { *m = MercuryMultiGetReply{} }
func (m *MercuryMultiGetReply) String() string            { return proto.CompactTextString(m) }
func (*MercuryMultiGetReply) ProtoMessage()               {}
func (*MercuryMultiGetReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MercuryMultiGetReply) GetReply() []*MercuryReply {
	if m != nil {
		return m.Reply
	}
	return nil
}

type MercuryRequest struct {
	Uri              *string `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
	ContentType      *string `protobuf:"bytes,2,opt,name=content_type,json=contentType" json:"content_type,omitempty"`
	Body             []byte  `protobuf:"bytes,3,opt,name=body" json:"body,omitempty"`
	Etag             []byte  `protobuf:"bytes,4,opt,name=etag" json:"etag,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *MercuryRequest) Reset()                    { *m = MercuryRequest{} }
func (m *MercuryRequest) String() string            { return proto.CompactTextString(m) }
func (*MercuryRequest) ProtoMessage()               {}
func (*MercuryRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MercuryRequest) GetUri() string {
	if m != nil && m.Uri != nil {
		return *m.Uri
	}
	return ""
}

func (m *MercuryRequest) GetContentType() string {
	if m != nil && m.ContentType != nil {
		return *m.ContentType
	}
	return ""
}

func (m *MercuryRequest) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

func (m *MercuryRequest) GetEtag() []byte {
	if m != nil {
		return m.Etag
	}
	return nil
}

type MercuryReply struct {
	StatusCode       *int32                    `protobuf:"zigzag32,1,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	StatusMessage    *string                   `protobuf:"bytes,2,opt,name=status_message,json=statusMessage" json:"status_message,omitempty"`
	CachePolicy      *MercuryReply_CachePolicy `protobuf:"varint,3,opt,name=cache_policy,json=cachePolicy,enum=MercuryReply_CachePolicy" json:"cache_policy,omitempty"`
	Ttl              *int32                    `protobuf:"zigzag32,4,opt,name=ttl" json:"ttl,omitempty"`
	Etag             []byte                    `protobuf:"bytes,5,opt,name=etag" json:"etag,omitempty"`
	ContentType      *string                   `protobuf:"bytes,6,opt,name=content_type,json=contentType" json:"content_type,omitempty"`
	Body             []byte                    `protobuf:"bytes,7,opt,name=body" json:"body,omitempty"`
	XXX_unrecognized []byte                    `json:"-"`
}

func (m *MercuryReply) Reset()                    { *m = MercuryReply{} }
func (m *MercuryReply) String() string            { return proto.CompactTextString(m) }
func (*MercuryReply) ProtoMessage()               {}
func (*MercuryReply) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MercuryReply) GetStatusCode() int32 {
	if m != nil && m.StatusCode != nil {
		return *m.StatusCode
	}
	return 0
}

func (m *MercuryReply) GetStatusMessage() string {
	if m != nil && m.StatusMessage != nil {
		return *m.StatusMessage
	}
	return ""
}

func (m *MercuryReply) GetCachePolicy() MercuryReply_CachePolicy {
	if m != nil && m.CachePolicy != nil {
		return *m.CachePolicy
	}
	return MercuryReply_CACHE_NO
}

func (m *MercuryReply) GetTtl() int32 {
	if m != nil && m.Ttl != nil {
		return *m.Ttl
	}
	return 0
}

func (m *MercuryReply) GetEtag() []byte {
	if m != nil {
		return m.Etag
	}
	return nil
}

func (m *MercuryReply) GetContentType() string {
	if m != nil && m.ContentType != nil {
		return *m.ContentType
	}
	return ""
}

func (m *MercuryReply) GetBody() []byte {
	if m != nil {
		return m.Body
	}
	return nil
}

type Header struct {
	Uri              *string      `protobuf:"bytes,1,opt,name=uri" json:"uri,omitempty"`
	ContentType      *string      `protobuf:"bytes,2,opt,name=content_type,json=contentType" json:"content_type,omitempty"`
	Method           *string      `protobuf:"bytes,3,opt,name=method" json:"method,omitempty"`
	StatusCode       *int32       `protobuf:"zigzag32,4,opt,name=status_code,json=statusCode" json:"status_code,omitempty"`
	UserFields       []*UserField `protobuf:"bytes,6,rep,name=user_fields,json=userFields" json:"user_fields,omitempty"`
	XXX_unrecognized []byte       `json:"-"`
}

func (m *Header) Reset()                    { *m = Header{} }
func (m *Header) String() string            { return proto.CompactTextString(m) }
func (*Header) ProtoMessage()               {}
func (*Header) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *Header) GetUri() string {
	if m != nil && m.Uri != nil {
		return *m.Uri
	}
	return ""
}

func (m *Header) GetContentType() string {
	if m != nil && m.ContentType != nil {
		return *m.ContentType
	}
	return ""
}

func (m *Header) GetMethod() string {
	if m != nil && m.Method != nil {
		return *m.Method
	}
	return ""
}

func (m *Header) GetStatusCode() int32 {
	if m != nil && m.StatusCode != nil {
		return *m.StatusCode
	}
	return 0
}

func (m *Header) GetUserFields() []*UserField {
	if m != nil {
		return m.UserFields
	}
	return nil
}

type UserField struct {
	Key              *string `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value            []byte  `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserField) Reset()                    { *m = UserField{} }
func (m *UserField) String() string            { return proto.CompactTextString(m) }
func (*UserField) ProtoMessage()               {}
func (*UserField) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UserField) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *UserField) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*MercuryMultiGetRequest)(nil), "MercuryMultiGetRequest")
	proto.RegisterType((*MercuryMultiGetReply)(nil), "MercuryMultiGetReply")
	proto.RegisterType((*MercuryRequest)(nil), "MercuryRequest")
	proto.RegisterType((*MercuryReply)(nil), "MercuryReply")
	proto.RegisterType((*Header)(nil), "Header")
	proto.RegisterType((*UserField)(nil), "UserField")
	proto.RegisterEnum("MercuryReply_CachePolicy", MercuryReply_CachePolicy_name, MercuryReply_CachePolicy_value)
}

func init() { proto.RegisterFile("mercury.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 414 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x9c, 0x92, 0xcf, 0x6e, 0xd3, 0x40,
	0x10, 0xc6, 0xe5, 0x38, 0x49, 0xc9, 0xd8, 0x0e, 0xce, 0xaa, 0xaa, 0xcc, 0x09, 0x30, 0x42, 0x2a,
	0x42, 0xf2, 0xa1, 0x1c, 0xe1, 0x40, 0xb1, 0x0a, 0xad, 0x44, 0xa0, 0x5a, 0xb5, 0x5c, 0x2d, 0x63,
	0x0f, 0xad, 0x85, 0x1d, 0x9b, 0xfd, 0x83, 0xe4, 0xe7, 0xe1, 0x11, 0x78, 0x41, 0x76, 0xbd, 0x76,
	0x9c, 0x10, 0x71, 0xe1, 0xf6, 0xcd, 0x6f, 0x26, 0xb3, 0xdf, 0x7c, 0x31, 0x78, 0x15, 0xb2, 0x4c,
	0xb2, 0x36, 0x6a, 0x58, 0x2d, 0xea, 0x30, 0x86, 0x93, 0xb5, 0x01, 0x6b, 0x59, 0x8a, 0xe2, 0x03,
	0x0a, 0x8a, 0x3f, 0x24, 0x72, 0x41, 0x5e, 0xc0, 0x11, 0x33, 0x32, 0xb0, 0x9e, 0xd8, 0xa7, 0xce,
	0xd9, 0xc3, 0xa8, 0x9f, 0xec, 0x27, 0xe8, 0xd0, 0x0f, 0x5f, 0xc3, 0xf1, 0xc1, 0x92, 0xa6, 0x6c,
	0xc9, 0x33, 0x98, 0x31, 0x2d, 0xfa, 0x05, 0xde, 0xb8, 0x40, 0x41, 0x6a, 0x7a, 0x61, 0x05, 0xcb,
	0xfd, 0xbd, 0xc4, 0x07, 0x5b, 0xb2, 0x42, 0xfd, 0xc8, 0x3a, 0x5d, 0x50, 0x2d, 0xc9, 0x53, 0x70,
	0xb3, 0x7a, 0x23, 0x70, 0x23, 0x12, 0xd1, 0x36, 0x18, 0x4c, 0xba, 0x96, 0xd3, 0xb3, 0x1b, 0x85,
	0x08, 0x81, 0xe9, 0xd7, 0x3a, 0x6f, 0x03, 0x5b, 0xb5, 0x5c, 0xda, 0x69, 0xcd, 0x50, 0xa4, 0x77,
	0xc1, 0xd4, 0x30, 0xad, 0xc3, 0xdf, 0x13, 0x70, 0x77, 0x6d, 0x90, 0xc7, 0xe0, 0x70, 0x91, 0x0a,
	0xc9, 0x93, 0xac, 0xce, 0xb1, 0x7b, 0x75, 0x45, 0xc1, 0xa0, 0x58, 0x11, 0xf2, 0x1c, 0x96, 0xfd,
	0x40, 0x85, 0x9c, 0xa7, 0x77, 0xc3, 0xf3, 0x9e, 0xa1, 0x6b, 0x03, 0xc9, 0x1b, 0xe5, 0x31, 0xcd,
	0xee, 0x31, 0x69, 0xea, 0xb2, 0xc8, 0x8c, 0x91, 0xe5, 0xd9, 0xa3, 0xbd, 0x9b, 0xa3, 0x58, 0x4f,
	0x5c, 0x77, 0x03, 0xca, 0xfe, 0x58, 0xe8, 0x9b, 0x85, 0x28, 0x3b, 0xa7, 0x2b, 0xaa, 0xe5, 0xd6,
	0xfc, 0x6c, 0x34, 0x7f, 0x90, 0xc3, 0xfc, 0xdf, 0x39, 0x1c, 0x8d, 0x39, 0x84, 0x6f, 0xc1, 0xd9,
	0x79, 0x98, 0xb8, 0xf0, 0x20, 0x3e, 0x8f, 0x2f, 0x2f, 0x92, 0x4f, 0x9f, 0x7d, 0x8b, 0xac, 0xc0,
	0x33, 0xd5, 0x35, 0xbd, 0xfa, 0x72, 0x7e, 0x73, 0xe1, 0x4f, 0x94, 0x19, 0xb7, 0x47, 0xb7, 0xef,
	0x3e, 0x5e, 0xc5, 0xbe, 0x1d, 0xfe, 0xb2, 0x60, 0x7e, 0x89, 0x69, 0x8e, 0xec, 0xff, 0xfe, 0x9d,
	0x13, 0x98, 0x57, 0x28, 0xee, 0xeb, 0xbc, 0x8b, 0x65, 0x41, 0xfb, 0xea, 0xef, 0xf0, 0xa7, 0x07,
	0xe1, 0xbf, 0x04, 0x47, 0x72, 0x64, 0xc9, 0xb7, 0x02, 0xcb, 0x9c, 0xab, 0x83, 0xf5, 0x87, 0x04,
	0xd1, 0xad, 0x62, 0xef, 0x35, 0xa2, 0x20, 0x07, 0xc9, 0xc3, 0x57, 0xb0, 0xd8, 0x36, 0xb4, 0xcf,
	0xef, 0xd8, 0x0e, 0x3e, 0x95, 0x24, 0xc7, 0x30, 0xfb, 0x99, 0x96, 0xd2, 0x18, 0x74, 0xa9, 0x29,
	0xfe, 0x04, 0x00, 0x00, 0xff, 0xff, 0xb6, 0xc0, 0xa9, 0x39, 0x11, 0x03, 0x00, 0x00,
}
